name: Frontend bug report
description: Report a problem with the palettum frontend
labels: [bug, frontend]
body:
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Checklist
      description:
      options:
        - label: I'm reporting a problem with palettum
          required: true
        - label: I've verified that I'm on the default branch
          required: true
        - label: I've searched the [issues and pull requests](https://github.com/arrowpc/palettum/issues?q=) for similar reports
          required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: Describe what isn't working
      placeholder: |
        For example:
        - Eyedrop tool not working
        - Can't select valid image type
        - Saving image not working
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to trigger the problem
      placeholder: |
        1. Go to X
        2. Click on Y
        3. See problem Z
    validations:
      required: true

  - type: input
    id: versions
    attributes:
      label: OS/arch, browser, & runtime versions
      placeholder: macOS 14.1 (ARM64), Chromium Engine Version 132.0.6834.84, Bun 1.0.21
     validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots showing the problem
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Any other relevant information
      placeholder: Console errors, attempted solutions, etc.
    validations:
      required: false
