name: Bug report
description: Report a problem you've encountered
labels: [bug]
body:
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Checklist
      options:
        - label: I'm reporting a problem with Palettum
          required: true
        - label: I've verified that I'm on the default branch
          required: true
        - label: I've searched the [issues and pull requests](https://github.com/arrowpc/palettum/issues?q=) for similar reports
          required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: Describe what isn't working
      placeholder: |
        For example:
        - Unexpected behavior when...
        - Error occurs during...
        - Integration between apps not working
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to trigger the problem
      placeholder: |
        1. Do X
        2. Then Y
        3. See problem Z
    validations:
      required: true

  - type: input
    id: versions
    attributes:
      label: System & version info
      description: Include relevant versions (OS, Python, C++ compiler, browser, runtime)
      placeholder: macOS 14.1 (ARM64), Python 3.13.1, Clang 16.0.0 Chromium Engine Version 132.0.6834.84, Bun 1.0.21
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots showing the problem
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Any other relevant information
      placeholder: Error messages, system setup, attempted solutions, etc.
    validations:
      required: false
