[package]
name = "palettum"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
image.workspace = true
log.workspace = true
rayon.workspace = true
thiserror.workspace = true
num_cpus.workspace = true
bon = "3.6.3"
strum_macros = "0.27"
anydir = "0.1.2"

serde = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
tsify = { workspace = true, optional = true }

tabled = {workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde_json.workspace = true
include_dir = "0.7"
env_home = "0.1.0"


[features]
wasm = ["dep:wasm-bindgen", "dep:serde", "dep:tsify", "image/serde"]
cli = ["dep:clap", "dep:tabled"]
