[package]
name = "palettum"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
image = { workspace = true, features = ["png", "jpeg", "webp", "gif"] }
log.workspace = true
rayon.workspace = true
thiserror.workspace = true
num_cpus.workspace = true
serde = { workspace = true, optional = true }

[features]
default = ["image/png", "image/gif"]
profiling = ["dep:pprof", "dep:prost"]
serde = ["dep:serde", "image/serde"]

[dependencies.pprof]
workspace = true
optional = true

[dependencies.prost]
workspace = true
optional = true
