name: API Tests

on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/api_test.yml'
      - 'apps/api/**'
  pull_request:
    paths:
      - '.github/workflows/api_test.yml'
      - 'apps/api/**'

defaults:
  run:
    working-directory: apps/api

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Install OpenMP
        if: runner.os == 'macOS'
        run: |
          brew install libomp

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/apps/core/external/vcpkg
          runVcpkgInstall: true

      - name: Build and Install palettum
        working-directory: apps/core
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          fi
          pip install .

      - name: Run Tests
        run: pytest
