name: Build CLI

on:
  push:
    paths:
      - "packages/**"
      - "Cargo.toml"
      - ".github/workflows/build-cli.yml"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            artifact_name: palettum-linux-x86_64
          - target: aarch64-unknown-linux-gnu
            artifact_name: palettum-linux-aarch64
          - target: x86_64-apple-darwin
            artifact_name: palettum-macos-x86_64
          - target: aarch64-apple-darwin
            artifact_name: palettum-macos-aarch64
          - target: x86_64-pc-windows-gnu
            artifact_name: palettum-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          # For Windows
          sudo apt-get install -y mingw-w64
          # For aarch64 Linux
          sudo apt-get install -y gcc-aarch64-linux-gnu
          # For macOS (optional, see note below)
          # You may need osxcross or zig for macOS targets

      - name: Build CLI
        run: cargo build --release -p palettum-cli --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          BIN=palettum
          EXT=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            EXT=".exe"
          fi
          cp target/${{ matrix.target }}/release/$BIN$EXT ${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
          if-no-files-found: error
