name: clang-format Check

on:
  push:
    paths:
      - '.github/workflows/clang-format-check.yml'
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - '.github/workflows/clang-format-check.yml'
      - 'src/**'
      - 'tests/**'
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'tests'
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          check-path: ${{ matrix.path }}
