name: Core Python Tests

on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/core_python_test.yml'
      - 'apps/core/tests/test_images/**'
      - 'apps/core/**/CMakeLists.txt'
      - 'apps/core/CMakeLists.txt'
      - 'apps/core/**/*.cmake'
      - 'apps/core/**.cpp'
      - 'apps/core/**.h'
      - 'apps/core/**.py'
  pull_request:
    paths:
      - '.github/workflows/core_python_test.yml'
      - 'apps/core/tests/test_images/**'
      - 'apps/core/**/CMakeLists.txt'
      - 'apps/core/CMakeLists.txt'
      - 'apps/core/**/*.cmake'
      - 'apps/core/**.cpp'
      - 'apps/core/**.h'
      - 'apps/core/**.py'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, windows-2019 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/core
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Install dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y autoconf automake autoconf-archive build-essential
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install autoconf automake autoconf-archive libomp
          fi

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/apps/core/external/vcpkg
          runVcpkgInstall: true

      - name: Build and Install palettum
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          fi
          pip install .

      - name: Run Python tests
        run: pytest tests/python/
