name: Core Python Tests

on:
  push:
    paths:
      - '.github/workflows/core_python_test.yml'
      - 'apps/core/tests/test_images/**'
      - 'apps/core/**/CMakeLists.txt'
      - 'apps/core/CMakeLists.txt'
      - 'apps/core/**/*.cmake'
      - 'apps/core/**.cpp'
      - 'apps/core/**.h'
      - 'apps/core/**.py'
  pull_request:
    paths:
      - '.github/workflows/core_python_test.yml'
      - 'apps/core/tests/test_images/**'
      - 'apps/core/**/CMakeLists.txt'
      - 'apps/core/CMakeLists.txt'
      - 'apps/core/**/*.cmake'
      - 'apps/core/**.cpp'
      - 'apps/core/**.h'
      - 'apps/core/**.py'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/core
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Build OpenCV
        if: runner.os != 'Windows'
        run: |
          mkdir -p opencv_build/x86_64 && cd opencv_build/x86_64
          cmake -D CMAKE_BUILD_TYPE=RELEASE \
                  -D CMAKE_INSTALL_PREFIX=$(pwd) \
                  -D BUILD_LIST=core,imgcodecs \
                  -D BUILD_EXAMPLES=OFF \
                  -D BUILD_TESTS=OFF \
                  -D BUILD_PERF_TESTS=OFF \
                  -D WITH_IPP=OFF \
                  -D WITH_OPENEXR=OFF \
                  ../../external/opencv
          make -j$(nproc)

      - name: Build OpenCV (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -Type Directory -Path opencv_build\AMD64
          cd opencv_build\AMD64
          cmake -D CMAKE_BUILD_TYPE=RELEASE `
                -D CMAKE_INSTALL_PREFIX=$PWD.Path `
                -D BUILD_LIST=core,imgcodecs `
                -D BUILD_EXAMPLES=OFF `
                -D BUILD_TESTS=OFF `
                -D BUILD_PERF_TESTS=OFF `
                -D WITH_IPP=OFF `
                -D WITH_OPENEXR=OFF `
                ..\..\external\opencv
          cmake --build . --config Release --parallel

      - name: Build and Install palettum
        if: runner.os != 'Windows'
        run: |
          pip install .

      - name: Build and Install palettum (Windows)
        if: runner.os == 'Windows'
        run: |
          python setup.py install bdist_wheel
          
          $wheels = Get-ChildItem -Path dist -Filter "*win_amd64.whl"
          foreach ($wheel in $wheels) {
            delvewheel repair $wheel.FullName --add-path opencv_build\AMD64\bin\Release
            pip install $wheel.FullName
          }

      - name: Run Python tests
        run: pytest tests/python/
