name: Core Python Tests

on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/core_python_test.yml'
      - 'apps/core/tests/test_images/**'
      - 'apps/core/**/CMakeLists.txt'
      - 'apps/core/CMakeLists.txt'
      - 'apps/core/**/*.cmake'
      - 'apps/core/**.cpp'
      - 'apps/core/**.h'
      - 'apps/core/**.py'
  pull_request:
    paths:
      - '.github/workflows/core_python_test.yml'
      - 'apps/core/tests/test_images/**'
      - 'apps/core/**/CMakeLists.txt'
      - 'apps/core/CMakeLists.txt'
      - 'apps/core/**/*.cmake'
      - 'apps/core/**.cpp'
      - 'apps/core/**.h'
      - 'apps/core/**.py'

env:
  OPENCV_VERSION: 4.8.0

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, windows-2019 ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: apps/core
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Install OpenMP
        if: runner.os == 'macOS'
        run: |
          brew install libomp

      - name: Build and Install palettum
        run: |
          case "$RUNNER_OS" in
          macOS)
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          ;;
          esac
          pip install .

      - name: Run Python tests
        run: pytest tests/python/
