name: C++ Test

on:
  push:
    paths:
      - '.github/workflows/cpp_test.yml'
      - 'src/**'
      - 'tests/cpp/**'
      - 'tests/test_images/**'
  pull_request:
    paths:
      - '.github/workflows/cpp_test.yml'
      - 'src/**'
      - 'tests/cpp/**'
      - 'tests/test_images/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
          cmake \
          libopencv-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Create build directory
        run: mkdir build-test

      - name: Configure CMake
        working-directory: build-test
        run: cmake ..

      - name: Build project
        working-directory: build-test
        run: make -j$(nproc)

      - name: Run tests
        working-directory: build-test
        run: ctest --output-on-failure

#      - name: Upload intermediate result
#        uses: actions/upload-artifact@v3
#        with:
#          name: intermediate-artifact
#          path: /home/runner/work/Palettum-Core/Palettum-Core/tests/intermediate.png