name: Formatting Check

on:
  push:
    paths:
      - '.github/workflows/format.yml'
      - '**.cpp'
      - '**.h'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/format.yml'
      - '**.cpp'
      - '**.h'
      - '**.py'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Python formatting with Black
        uses: psf/black@stable
        with:
          path: apps/api

  cpp-formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check C++ formatting with clang-format
        uses: jidicula/clang-format-action@v4.11.0
