name: Python Test

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'tests/python/**'
      - 'tests/test_images/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'tests/python/**'
      - 'tests/test_images/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest opencv-python

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake \
          libopencv-dev \

      - name: Build and Install palettum
        run: |
          pip install .

      - name: Run Python tests
        run: pytest tests/python/