name: Build and Release CLI

on:
  push:
    paths:
      - "cli/**"
      - "core/**"
      - "wasm/**"
      - "Cargo.toml"
      - ".github/workflows/code-quality.yml"
    tags:
      - "v*"

jobs:
  build:
    name: Build - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os_name: Linux-aarch64
            os: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os_name: Linux-riscv64
            os: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - os_name: Windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc

          - os_name: macOS-x86_64
            os: macos-13
            target: x86_64-apple-darwin

          - os_name: macOS-aarch64
            os: macos-15
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build palettum-cli
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release -p cli"
          strip: true

      - name: Publish artifact
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: palettum
          target: ${{ matrix.platform.target }}
          changes-file: ""

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: palettum
          target: ${{ matrix.platform.target }}
          changes-file: ""
