name: Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
          cmake \
          libopencv-dev

      - name: Create build directory
        run: mkdir build-test

      - name: Configure CMake
        working-directory: build-test
        run: cmake ..

      - name: Build project
        working-directory: build-test
        run: make

      - name: Run tests
        working-directory: build-test
        run: ctest