name: Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
          cmake \
          libopencv-dev

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Create build directory
        run: mkdir build-test

      - name: Configure CMake
        working-directory: build-test
        run: cmake ..

      - name: Build project
        working-directory: build-test
        run: make

      - name: Run tests
        working-directory: build-test
        run: ctest --output-on-failure

      - name: Display test logs
        if: failure()
        run: cat /home/runner/work/Palettum-Core/Palettum-Core/build-test/Testing/Temporary/LastTest.log