name: Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
          cmake

      - name: Load OpenCV from cache
        id: opencv
        uses: actions/cache@v3
        with:
          path: opencv-4.8.0
          key: opencv-4.8.0

      - name: Build and install OpenCV 4.8.0 from source
        if: steps.opencv.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/opencv/opencv.git
          cd opencv
          git checkout tags/4.8.0
          mkdir build && cd build
          cmake -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_EXAMPLES=OFF ..
          make -j$(nproc)
          sudo make install
          cd $GITHUB_WORKSPACE

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Create build directory
        run: mkdir build-test

      - name: Configure CMake
        working-directory: build-test
        run: cmake ..

      - name: Build project
        working-directory: build-test
        run: make

      - name: Run tests
        continue-on-error: true
        working-directory: build-test
        run: ctest --output-on-failure

      - name: Upload intermediate result
        uses: actions/upload-artifact@v3
        with:
          name: intermediate-artifact
          path: /home/runner/work/Palettum-Core/Palettum-Core/tests/intermediate.png
